FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime
WORKDIR /workspace
COPY requirements.txt requirements.txt
COPY lib/apex apex
RUN pip install -r requirements.txt && \
    export LC_ALL=C.UTF-8 && \
    export LANG=C.UTF-8 && \
    wandb login 75f27c17f5a086fd6a52941402e6e823efb21d65 &&  \
    (cd apex; pip install -v --no-cache-dir ./) && \
    pip install jupyter_contrib_nbextensions && \
    pip install jupyter_nbextensions_configurator && \
    jupyter contrib nbextension install --user && \
    jupyter nbextension enable codefolding/main && \
    jupyter nbextension enable hinterland/hinterland && \
    jupyter nbextension enable scratchpad/main
    



